services:
  github-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-proxy:latest
    container_name: github-proxy
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"  # 主服务端口
      - "${API_PORT:-3001}:3001"  # API服务端口
    volumes:
      - ./data:/app/data  # 持久化数据目录
      - ./logs:/app/logs  # 持久化日志目录
      - ./.env:/app/.env  # 配置文件
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai  # 设置时区
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - github-proxy-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true

networks:
  github-proxy-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
